spring.application.name=diario

api.security.token.secret=minha-chave-secreta-muito-dificil-de-adivinhar-12345

spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres?user=postgres.lwzqtwedyxkcthdceysh&password=diariodebordo
spring.datasource.username=postgres
spring.datasource.password=diariodebordo
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver

## MAIL ##

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pedrokussy@gmail.com
spring.mail.password=lqpb vlqy jurv yyac
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true