spring.application.name=diario

api.security.token.secret=minha-chave-secreta-muito-dificil-de-adivinhar-12345

spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres?user=postgres.lwzqtwedyxkcthdceysh&password=diariodebordo
spring.datasource.username=postgres
spring.datasource.password=diariodebordo


spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=org.postgresql.Driver